E-Nutrition Main Project/E-Nutriton/Controllers/ErrorLogController.cs
using E_Nutriton.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Nutriton.Controllers
{
    public class ErrorLogController : Controller
    {
        db_enutritionEntities dbModel = new db_enutritionEntities();

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetData()
        {
            using (db_enutritionEntities dbModel = new db_enutritionEntities())
            {
                List<tbl_error_log> errorList = dbModel.tbl_error_log.ToList<tbl_error_log>();
                List<ErrorOutput> result = new List<ErrorOutput>();
                foreach (var item in errorList)
                {

                    result.Add(new ErrorOutput
                    {
                        id_error = item.id_error,
                        error_line = item.error_line,
                        performed_by = item.performed_by,
                        error_time = item.error_time.ToString(),
                        error_description = item.error_description
                    });
                }

                return Json(new { data = result.OrderByDescending(e => e.id_error) }, JsonRequestBehavior.AllowGet);
            }
        }

        public class ErrorOutput
        {
            public int id_error { get; set; }
            public string error_line { get; set; }
            public string performed_by { get; set; }
            public string error_time { get; set; }
            public string error_description { get; set; }
        }
    }
}

E-Nutrition Main Project/E-Nutriton/Views/ErrorLog/Index.cshtml
@model E_Nutriton.Models.tbl_error_log
@{
    ViewBag.Title = "Error Log";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<div id="main-content">
    <div class="container-fluid">
        <h2>Error Log</h2>
        <div>
            <br />

            <table id="errorlog" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Error Path</th>
                        <th>performed by</th>
                        <th>Error Time</th>
                        <th>Description</th>
                    </tr>
                </thead>
            </table>


            <link href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap.min.css" rel="stylesheet" />
            <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

            @section scripts {
                <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
                <script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap.min.js"></script>

                <script src="~/Scripts/notify.min.js"></script>

                <script>
                    var Popup, dataTable;
                    $(document).ready(function () {
                        dataTable = $('#errorlog').DataTable({
                            "ajax": {
                                "url": "@Url.Action("GetData", "ErrorLog")",
                                "type": "GET",
                                "datatype": "json"
                            },
                            "columns": [
                                { "data": "error_line" },
                                { "data": "performed_by" },
                                { "data": "error_time" },
                                { "data": "error_description" }
                            ], "order": [],
                            "language": {
                                "emptyTable": "No data Audit"
                            }
                        });
                    });
                    function PopupForm(url) {
                        var formDiv = $('<div/>');
                        $.get(url)
                            .done(function (response) {
                                formDiv.html(response);

                                Popup = formDiv.dialog({
                                    autoOpen: true,
                                    resizable: false,
                                    title: 'Fill Food Detail',
                                    height: 550,
                                    width: 700,
                                    close: function () {
                                        Popup.dialog('destroy').remove();
                                    }

                                });
                            });
                    }

                    function SubmitForm(form) {
                        $.validator.unobtrusive.parse(form);
                        if ($(form).valid()) {
                            $.ajax({
                                type: "POST",
                                url: form.action,
                                data: $(form).serialize(),
                                success: function (data) {
                                    if (data.success) {
                                        Popup.dialog('close');
                                        dataTable.ajax.reload();

                                        $.notify(data.message, {
                                            globalPosition: "top center",
                                            className: "success"
                                        })
                                    }
                                }
                            });
                        }
                        return false;
                    }


                </script>
            }

        </div>
    </div>
</div>