E-Nutrition Main Project/E-Nutriton/Controllers/DiseaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using E_Nutriton.Models;
using System.Data.Entity;

namespace E_Nutriton.Controllers
{
    public class DiseaseController : Controller
    {
        // GET: Disease
        db_enutritionEntities dbModel = new db_enutritionEntities();

        public ActionResult Index()
        {
            return View();
        }
        
        [HttpGet]
        public JsonResult GetData()
        {
            using (db_enutritionEntities dbModel = new db_enutritionEntities())
            {
                //List<tbl_disease> diseaseList = dbModel.tbl_disease.ToList<tbl_disease>();
                //return Json(new { data = diseaseList }, JsonRequestBehavior.AllowGet);
                List<tbl_disease> diseaseList = dbModel.tbl_disease.ToList<tbl_disease>();
                List<DiseaseOutput> result = new List<DiseaseOutput>();
                foreach (var item in diseaseList)
                {

                    result.Add(new DiseaseOutput
                    {
                        id_disease = item.id_disease,
                        name_disease = item.name_disease,
                        energy = Convert.ToInt32(item.energy)
                    });
                }

                return Json(new { data = result.OrderByDescending(e => e.id_disease) }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult AddorEdit(int id = 0)
        {
            if (id == 0)
                return View(new tbl_disease());
            else
            {
                using (db_enutritionEntities dbModel = new db_enutritionEntities())
                {
                    return View(dbModel.tbl_disease.Where(x => x.id_disease == id).FirstOrDefault<tbl_disease>());
                }
            }
        }

        [HttpPost]
        public ActionResult AddorEdit(tbl_disease disease)
        {
            using (var transaction = dbModel.Database.BeginTransaction())
            {
                try
                {
                    if (disease.id_disease == 0)
                    {
                        dbModel.tbl_disease.Add(disease);
                        tbl_audit_trail audit = new tbl_audit_trail
                        {
                            table_name = "tbl_disease",
                            operation = "ADD",
                            occured_at = DateTime.Now,
                            performed_by = Session["Username"].ToString(),
                            description = "Add new Disease" + disease.name_disease
                        };
                        dbModel.tbl_audit_trail.Add(audit);

                        dbModel.SaveChanges();
                        transaction.Commit();
                        return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        dbModel.Entry(disease).State = EntityState.Modified;
                        tbl_audit_trail audit = new tbl_audit_trail
                        {
                            table_name = "tbl_disease",
                            operation = "EDIT",
                            occured_at = DateTime.Now,
                            performed_by = Session["Username"].ToString(),
                            description = "Edit Disease " + disease.name_disease
                        };
                        dbModel.tbl_audit_trail.Add(audit);

                        dbModel.SaveChanges();
                        transaction.Commit();
                        return Json(new { success = true, message = "Update Successfully" }, JsonRequestBehavior.AllowGet);

                    }
                }
                catch (Exception msgError)
                {
                    db_enutritionEntities dbModel2 = new db_enutritionEntities();

                    tbl_error_log errlog = new tbl_error_log()
                    {
                        error_line = msgError.StackTrace,
                        error_time = DateTime.Now,
                        performed_by = Session["Username"].ToString(),
                        error_description = msgError.Message
                    };
                    dbModel2.tbl_error_log.Add(errlog);
                    dbModel2.SaveChanges();
                    transaction.Rollback();
                    return Json(new { success = true, message = "Error " + msgError.Message }, JsonRequestBehavior.AllowGet);
                } 
            }

        }

        public ActionResult Delete(int id)
        {
            using (db_enutritionEntities dbModel = new db_enutritionEntities())
            {
                tbl_disease disease = dbModel.tbl_disease.Where(x => x.id_disease == id).FirstOrDefault<tbl_disease>();
                dbModel.tbl_disease.Remove(disease);
                tbl_audit_trail audit = new tbl_audit_trail
                {
                    table_name = "tbl_disease",
                    operation = "DELETE",
                    occured_at = DateTime.Now,
                    performed_by = Session["Username"].ToString(),
                    description = "Delete Disease " + disease.name_disease
                };
                dbModel.tbl_audit_trail.Add(audit);

                dbModel.SaveChanges();
                return Json(new { success = true, message = "delete Successfully" }, JsonRequestBehavior.AllowGet);

            }

        }

        public class DiseaseOutput
        {
            public int id_disease { get; set; }
            public string name_disease { get; set; }
            public int energy { get; set; }
        }

    }
}

E-Nutrition Main Project/E-Nutriton/Views/Disease/AddorEdit.cshtml
@model E_Nutriton.Models.tbl_disease
@{
                /**/

                /**/

                Layout = null;
}

@using (Html.BeginForm("AddorEdit", "disease", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(Model => Model.id_disease)
    <div class="form-group">
        @Html.LabelFor(Model => Model.name_disease, new { @class = "controller-label" }) <a style="color:red">*</a>
        @Html.EditorFor(Model => Model.name_disease, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(Model => Model.name_disease, "", new { @class = "text-danger" })
    </div>
        
    <div class="form-group">
        @Html.LabelFor(Model => Model.energy, new { @class = "controller-label" }) <sup>(gr)</sup> <a style="color:red">*</a>
        @Html.EditorFor(Model => Model.energy, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(Model => Model.energy, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-primary" />
        <input type="reset" value="Reset" class="btn btn-warning" />
    </div>
}

E-Nutrition Main Project/E-Nutriton/Views/Disease/Index.cshtml
@model E_Nutriton.Models.tbl_disease
@{
    ViewBag.Title = "Disease List";
    Layout = "~/Views/Shared/_LayoutMaster.cshtml";
}

<div id="main-content">
    <div class="container-fluid">
        <h2>Disease List</h2>
        <div>
            <br />
            <a class="btn btn-primary" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddorEdit","Disease")')"><i class='fa fa-plus-circle'></i>add new</a>
            <table id="disease" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Name Disease</th>
                        <th>Energy <sup>(Kkal)</sup></th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>


            <link href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap.min.css" rel="stylesheet" />
            <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

            @section scripts {
                <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
                <script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap.min.js"></script>

                <script src="~/Scripts/notify.min.js"></script>

                <script>
                        var Popup, dataTable;
                        $(document).ready(function () {
                            dataTable = $('#disease').DataTable({
                                "ajax": {
                                    "url": "@Url.Action("GetData", "disease")",
                                    "type": "GET",
                                    "datatype": "json"
                                },
                                "columns": [
                                    { "data": "name_disease" },
                                    { "data": "energy" },
                                    {
                                        "data": "id_disease", "render": function (data) {
                                            return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("AddorEdit","Disease")/" + data +"')><i class='fa fa-pencil'></i>Edit</a>";
                                        },
                                        "orderable": false,
                                        "searchable": false,
                                        "width": "150px"
                                    }
                                ], "order": [],
                                "language": {
                                    "emptyTable": "No data Found, Please Click add new button"
                                }
                            });
                        });
                        function PopupForm(url) {
                            var formDiv = $('<div/>');
                            $.get(url)
                                .done(function (response) {
                                    formDiv.html(response);

                                    Popup = formDiv.dialog({
                                        autoOpen: true,
                                        resizable: false,
                                        title: 'Fill Disease Detail',
                                        height: 310,
                                        width: 500,
                                        close: function () {
                                            Popup.dialog('destroy').remove();
                                        }

                                    });
                                });
                        }

                        function SubmitForm(form) {
                            $.validator.unobtrusive.parse(form);
                            if ($(form).valid()) {
                                $.ajax({
                                    type: "POST",
                                    url: form.action,
                                    data: $(form).serialize(),
                                    success: function (data) {
                                        if (data.success) {
                                            Popup.dialog('close');
                                            dataTable.ajax.reload();

                                            $.notify(data.message, {
                                                globalPosition: "top center",
                                                className: "success"
                                            })
                                        }
                                    }
                                });
                            }
                            return false;
                        }


                </script>
            }

        </div>
    </div>
</div>